name: CD - Deploy to EC2 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_run:
    workflows: ["CI - Build and Push to ECR"] 
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- SECURITY SCANS ---
      
      # Run Gitleaks natively
      - name: Run Gitleaks natively
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
          ./gitleaks detect --source . --report-path gitleaks-report.json --report-format json || true

      # Trivy Vulnerability Scanner (Using Trivy's built-in container template path)
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-report.html'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
        continue-on-error: true

      # Upload Reports (Note: GitHub will zip these automatically!)
      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            gitleaks-report.json
            trivy-report.html
            
      # --- END SECURITY SCANS ---

      # 1. AWS Static Key Login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}    

      # 2. Get GitHub Runner IP natively
      - name: Get GitHub Runner IP
        id: runner-ip
        run: echo "ipv4=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT

      # 3. Open the AWS Security Group door JUST for this runner
      - name: Whitelist Runner IP
        run: |
          echo "Authorizing IP: ${{ steps.runner-ip.outputs.ipv4 }}/32 for SSH"
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.runner-ip.outputs.ipv4 }}/32

      # 4. Do the Secure Copy (SCP)
      - name: Copy docker-compose, nginx, and scripts to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,nginx/,scripts/"
          target: "/home/${{ secrets.EC2_USERNAME }}/meridian-retail"

      # 5. SSH in, set script permissions, and run the deployment
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URL }}
            
            # Make sure all shell scripts are executable
            chmod +x /home/${{ secrets.EC2_USERNAME }}/meridian-retail/scripts/*.sh

            # Move Nginx conf to system folders and reload
            sudo cp /home/${{ secrets.EC2_USERNAME }}/meridian-retail/nginx/meridian-http.conf /etc/nginx/sites-available/meridian
            sudo ln -sf /etc/nginx/sites-available/meridian /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t
            sudo systemctl reload nginx

            # Setup Docker Compose
            cd /home/${{ secrets.EC2_USERNAME }}/meridian-retail
            echo "IMAGE_TAG=${{ github.sha }}" > .env
            echo "ECR_REGISTRY_URL=${{ secrets.ECR_REGISTRY_URL }}" >> .env
            
            docker compose pull
            docker compose up -d

            # Provision TLS certificate via Certbot
            sudo certbot --nginx -d shop-meridian.duckdns.org --non-interactive --agree-tos -m bogreaper05@gmail.com --redirect --keep-until-expiring

      # 6. Revoke Runner IP with Safety Check
      - name: Revoke Runner IP
        if: always()
        run: |
          if [ -z "${{ steps.runner-ip.outputs.ipv4 }}" ]; then
            echo "No IP was fetched, skipping revoke."
          else
            echo "Revoking IP: ${{ steps.runner-ip.outputs.ipv4 }}/32 for SSH"
            aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.runner-ip.outputs.ipv4 }}/32 || true
          fi